#%RAML 1.0 ResourceType

traits:
  comman-header: !include /traits/headers-comman-trait.raml
  aoutherization-header: !include /traits/headers-jwt-authorization-trait.raml

types:
  error-dataType: !include /dataType/error-dataType.raml
  post-registration resquest: !include /dataType/post-registration-request-dataType.raml
  post-registration response: !include /dataType/post-registration-response-dataType.raml

   
    