#%RAML 1.0 Trait

headers:
  x-cms-transactionId:
    type: string
    required: true
    minLength: 36
    maxLength: 36
    example: "gdft-jshtfi-8574-jhbfrt-876954-nhfhh"
  ClientId:
    type: string
    required: true
    example: "gdft-jshtfi-1234-jhbfrt-876954-nhfhh"    
  ClientSecret:
    type: string
    required: true
    example: "gdft-jshtfi-4325-jhbfrt-876954-nhfhh"